### PR TITLE
Bump to 1.4.2, rely on libitk to correctly declare compatibility

### PR DESCRIPTION
**Pull request by effigies**
Updates to https://github.com/pyushkevich/c3d/commit/2abc64bfa8385941359ec6a5a34e77b0d0f4e8b1, which updated the version to 1.4.2.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by effigies** [comment]
@conda-forge-admin, please rerender

**Comment by effigies** [comment]
@pyushkevich @ghisvail This is successfully building again.

**Comment by effigies** [comment]
I've checked the build artifacts while building locally, this produces:

```
  "depends": [
    "__glibc >=2.17,<3.0.a0",
    "libgcc >=13",
    "libitk >=5.4.0,<5.5.0a0",
    "libstdcxx >=13"
  ],
```

And installing the package from the local build, `libitk` and `fftw` are pulled in:

```
❯ mamba create -n test -c ./build_artifacts/ -c conda-forge convert3d

Looking for: ['convert3d']

file:///home/chris/Projects/conda-forge/convert3.. Checked  0.0s
file:///home/chris/Projects/conda-forge/convert3.. Checked  0.0s
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
file:///home/chris/Projects/conda-forge/convert3.. 511.0 B @   3.3MB/s  0.0s
file:///home/chris/Projects/conda-forge/convert3..  96.0 B @   1.2MB/s  0.0s
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change
pkgs/main/linux-64                                            No change
pkgs/r/linux-64                                               No change
Transaction

  Prefix: /home/chris/mambaforge/envs/test

  Updating specs:

   - convert3d


  Package                 Version  Build                  Channel                                                                    Size
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex             0.1  conda_forge            conda-forge                                                              Cached
  + ca-certificates     2024.8.30  hbcca054_0             conda-forge                                                              Cached
  + libgomp                14.1.0  h77fa898_1             conda-forge                                                              Cached
  + _openmp_mutex             4.5  2_gnu                  conda-forge                                                              Cached
  + libgcc                 14.1.0  h77fa898_1             conda-forge                                                              Cached
  + c-ares                 1.34.1  heb4867d_0             conda-forge                                                              Cached
  + openssl                 3.3.2  hb9d3cd8_0             conda-forge                                                              Cached
  + libgfortran5           14.1.0  hc5f4f2c_1             conda-forge                                                              Cached
  + libdeflate               1.22  hb9d3cd8_0             conda-forge                                                              Cached
  + libzlib                 1.3.1  hb9d3cd8_2             conda-forge                                                              Cached
  + libexpat                2.6.3  h5888daf_0             conda-forge                                                              Cached
  + libgcc-ng              14.1.0  h69a702a_1             conda-forge                                                              Cached
  + libstdcxx              14.1.0  hc0a3c3a_1             conda-forge                                                              Cached
  + libgfortran            14.1.0  h69a702a_1             conda-forge                                                              Cached
  + libpng                 1.6.44  hadc24fc_0             conda-forge                                                              Cached
  + zlib                    1.3.1  hb9d3cd8_2             conda-forge                                                              Cached
  + expat                   2.6.3  h5888daf_0             conda-forge                                                              Cached
  + ncurses                   6.5  he02047a_1             conda-forge                                                              Cached
  + libev                    4.33  hd590300_2             conda-forge                                                              Cached
  + libiconv                 1.17  hd590300_2             conda-forge                                                              Cached
  + keyutils                1.6.1  h166bdaf_0             conda-forge                                                              Cached
  + libssh2                1.11.0  h0841786_0             conda-forge                                                              Cached
  + libwebp-base            1.4.0  hd590300_0             conda-forge                                                              Cached
  + xz                      5.2.6  h166bdaf_0             conda-forge                                                              Cached
  + libjpeg-turbo           3.0.0  hd590300_1             conda-forge                                                              Cached
  + libstdcxx-ng           14.1.0  h4852527_1             conda-forge                                                              Cached
  + libgfortran-ng         14.1.0  h69a702a_1             conda-forge                                                              Cached
  + libedit          3.1.20191231  he28a2e2_2             conda-forge                                                              Cached
  + eigen                   3.4.0  h00ab1b0_0             conda-forge                                                              Cached
  + libnghttp2             1.58.0  h47da74e_1             conda-forge                                                              Cached
  + icu                      75.1  he02047a_0             conda-forge                                                              Cached
  + zstd                    1.5.6  ha6fb4c9_0             conda-forge                                                              Cached
  + lerc                    4.0.0  h27087fc_0             conda-forge                                                              Cached
  + libaec                  1.1.3  h59595ed_0             conda-forge                                                              Cached
  + fftw                   3.3.10  nompi_hf1063bd_110     conda-forge                                                              Cached
  + krb5                   1.21.3  h659f571_0             conda-forge                                                              Cached
  + libxml2                2.12.7  he7c6b58_4             conda-forge                                                              Cached
  + libtiff                 4.7.0  he137b08_1             conda-forge                                                              Cached
  + libcurl                8.10.1  hbbe4b11_0             conda-forge                                                              Cached
  + libhwloc               2.11.1  default_hecaa2ac_1000  conda-forge                                                              Cached
  + hdf5                   1.14.3  nompi_hdf9ad27_105     conda-forge                                                              Cached
  + tbb                 2021.13.0  h84d6215_0             conda-forge                                                              Cached
  + libitk                  5.4.0  h5de25d7_3             conda-forge                                                              Cached
  + convert3d               1.4.2  hdfd8dae_0             /home/chris/Projects/conda-forge/convert3d-feedstock/build_artifacts     Cached

  Summary:

  Install: 44 packages

  Total download: 0 B

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n]
```

**Comment by ghisvail** [comment]
Thanks Chris

**Pull request merged**
